// <auto-generated />
namespace notfinal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class qoi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(qoi));
        
        string IMigrationMetadata.Id
        {
            get { return "202011030731023_qoi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
