// <auto-generated />
namespace hoangkhoa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class iqywer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(iqywer));
        
        string IMigrationMetadata.Id
        {
            get { return "202010191543409_iqywer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
